"""
StudioMap — Google OAuth Authentication
=========================================
Stateless OAuth 2.0 code flow.

The HMAC-signed state param means no session affinity is required —
any Cloud Run instance can verify a state token generated by any other.

Auth is skipped (dev mode) if google_client_id is not configured.
"""

import hashlib
import hmac
import time
import uuid
from urllib.parse import urlencode

import requests
import streamlit as st

from config import load_config

_GOOGLE_AUTH_URL     = "https://accounts.google.com/o/oauth2/v2/auth"
_GOOGLE_TOKEN_URL    = "https://oauth2.googleapis.com/token"
_GOOGLE_USERINFO_URL = "https://www.googleapis.com/oauth2/v3/userinfo"

_DEV_USER = {"email": "dev@local", "name": "Developer (no auth)", "picture": ""}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _session_id() -> str:
    """Stable session ID stored in URL ?sid= so it survives page refreshes."""
    sid = st.query_params.get("sid")
    if not sid:
        sid = uuid.uuid4().hex
        st.query_params["sid"] = sid
    return sid


def _make_state(secret: str, session_id: str) -> str:
    """Create a signed state token: <timestamp>:<HMAC>"""
    ts  = str(int(time.time()))
    sig = hmac.new(secret.encode(), (session_id + ts).encode(), hashlib.sha256).hexdigest()
    return f"{ts}:{sig}"


def _verify_state(secret: str, session_id: str, state: str) -> bool:
    """Verify state token; reject if older than 10 minutes."""
    try:
        ts, sig = state.split(":", 1)
        if int(time.time()) - int(ts) > 600:
            return False
        expected = hmac.new(
            secret.encode(), (session_id + ts).encode(), hashlib.sha256
        ).hexdigest()
        return hmac.compare_digest(sig, expected)
    except Exception:
        return False


# ── Public API ────────────────────────────────────────────────────────────────

def get_authorization_url(cfg: dict) -> str:
    secret = cfg.get("google_client_secret", "dev")
    state  = _make_state(secret, _session_id())
    params = {
        "client_id":     cfg["google_client_id"],
        "redirect_uri":  cfg["google_redirect_uri"],
        "response_type": "code",
        "scope":         "openid email profile",
        "state":         state,
        "access_type":   "offline",
        "prompt":        "select_account",
    }
    domain = cfg.get("google_workspace_domain", "")
    if domain:
        params["hd"] = domain
    return f"{_GOOGLE_AUTH_URL}?{urlencode(params)}"


def exchange_code(cfg: dict, code: str, state: str) -> dict | None:
    """Exchange OAuth code for user info. Returns None on any failure."""
    secret = cfg.get("google_client_secret", "dev")
    if not _verify_state(secret, _session_id(), state):
        return None

    try:
        token_resp = requests.post(_GOOGLE_TOKEN_URL, data={
            "code":          code,
            "client_id":     cfg["google_client_id"],
            "client_secret": cfg["google_client_secret"],
            "redirect_uri":  cfg["google_redirect_uri"],
            "grant_type":    "authorization_code",
        }, timeout=10)
        if not token_resp.ok:
            return None

        access_token = token_resp.json().get("access_token")
        user_resp    = requests.get(
            _GOOGLE_USERINFO_URL,
            headers={"Authorization": f"Bearer {access_token}"},
            timeout=10,
        )
        return user_resp.json() if user_resp.ok else None
    except Exception:
        return None


def require_login(cfg: dict) -> bool:
    """
    Returns True if the user is logged in.
    If not, renders the login page and returns False.
    Call this as the very first line of app.py main().
    """
    # Already logged in
    if st.session_state.get("user"):
        return True

    # OAuth not configured → dev mode, skip auth
    if not cfg.get("google_client_id") or not cfg.get("google_client_secret"):
        st.session_state["user"] = _DEV_USER
        return True

    # Handle OAuth callback (?code=...&state=...)
    code  = st.query_params.get("code")
    state = st.query_params.get("state")
    if code and state:
        with st.spinner("Signing you in…"):
            user = exchange_code(cfg, code, state)

        if user:
            domain = cfg.get("google_workspace_domain", "")
            if domain and not user.get("email", "").endswith(f"@{domain}"):
                st.error(
                    f"Access is restricted to **@{domain}** accounts. "
                    f"You signed in as `{user.get('email')}`. Please use your school account."
                )
                _render_login_page(cfg)
                return False

            st.session_state["user"] = user
            # Clean OAuth params from URL
            st.query_params.pop("code", None)
            st.query_params.pop("state", None)
            # Log login
            try:
                import activity
                activity.log_event(
                    activity.EventType.USER_LOGIN,
                    metadata={"email": user["email"]},
                    user_email=user["email"],
                    user_name=user.get("name", user["email"]),
                )
            except Exception:
                pass
            st.rerun()
            return False   # rerun handles transition
        else:
            st.error("Sign-in failed. Please try again.")

    _render_login_page(cfg)
    return False


def _render_login_page(cfg: dict):
    st.markdown("""
    <style>
    [data-testid="stSidebar"] { display: none; }
    .login-wrap {
        display: flex; justify-content: center;
        align-items: flex-start; padding-top: 10vh;
    }
    .login-card {
        background: white; border-radius: 16px;
        box-shadow: 0 4px 32px rgba(0,0,0,0.12);
        padding: 3rem 2.5rem; max-width: 400px;
        width: 100%; text-align: center;
    }
    .login-card h1 { margin-bottom: 0.25rem; font-size: 2rem; }
    .login-card p  { color: #666; margin-bottom: 1.5rem; }
    </style>
    <div class="login-wrap"><div class="login-card">
        <h1>🏫 StudioMap</h1>
    """, unsafe_allow_html=True)

    school = cfg.get("school_name", "")
    if school:
        st.markdown(f"**{school}**")
    st.markdown("Sign in to access your studio knowledge base.")

    auth_url = get_authorization_url(cfg)
    st.link_button("🔐 Sign in with Google", auth_url,
                   use_container_width=True, type="primary")

    domain = cfg.get("google_workspace_domain", "")
    if domain:
        st.caption(f"Access restricted to @{domain} accounts")

    st.markdown("</div></div>", unsafe_allow_html=True)


def render_logout_button():
    """Render user info + logout button in the sidebar."""
    user = st.session_state.get("user", {})
    if not user or user == _DEV_USER:
        return

    picture = user.get("picture", "")
    if picture:
        st.markdown(
            f'<img src="{picture}" width="40" style="border-radius:50%;margin-bottom:4px">',
            unsafe_allow_html=True
        )
    st.markdown(f"**{user.get('name', '')}**")
    st.caption(user.get("email", ""))

    if st.button("🚪 Sign Out", use_container_width=True):
        try:
            import activity
            activity.log_event(activity.EventType.USER_LOGOUT)
        except Exception:
            pass
        del st.session_state["user"]
        st.rerun()


def is_admin(cfg: dict) -> bool:
    """Returns True if the current user is the configured admin."""
    admin_email = cfg.get("admin_email", "")
    if not admin_email:
        return True   # no admin configured → everyone is admin (dev mode)
    user = st.session_state.get("user", {})
    return user.get("email", "") == admin_email


def require_admin(cfg: dict):
    """Stop rendering with an error if the current user is not admin."""
    if not is_admin(cfg):
        st.error("⛔ This action requires admin access.")
        st.stop()
